Update dependency on Hypothesis to its version 4.18.2
The reason of upgrade is that older versions of Hypothesis are
incompatible with Python 3.8 and commonmark's tests failed:

    % python commonmark/tests/unit_tests.py
    Traceback (most recent call last):
      File "commonmark/tests/unit_tests.py", line 6, in <module>
        from hypothesis import given, example
      :
      File "/path/to/virtualenv/lib/python3.8/site-packages/hypothesis/internal/compat.py", line 373, in update_code_location
        return type(code)(*unpacked)
    TypeError: an integer is required (got type bytes)

https://github.com/HypothesisWorks/hypothesis/issues/1943